In [2]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split 
from sklearn import metrics
from matplotlib import pyplot as plt
from sklearn import tree
from sklearn.decomposition import PCA

In [3]:
datafile = "../qsar-biodeg.csv"
df = pd.read_csv(datafile, header = 0)
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V33,V34,V35,V36,V37,V38,V39,V40,V41,Class
0,3.919,2.6909,0,0,0,0,0,31.4,2,0,...,0,0,0,2.949,1.591,0,7.253,0,0,2
1,4.170,2.1144,0,0,0,0,0,30.8,1,1,...,0,0,0,3.315,1.967,0,7.257,0,0,2
2,3.932,3.2512,0,0,0,0,0,26.7,2,4,...,0,0,1,3.076,2.417,0,7.601,0,0,2
3,3.000,2.7098,0,0,0,0,0,20.0,0,2,...,0,0,1,3.046,5.000,0,6.690,0,0,2
4,4.236,3.3944,0,0,0,0,0,29.4,2,4,...,0,0,0,3.351,2.405,0,8.003,0,0,2

In [5]:
x = df.loc[:, df.columns != 'Class']
y = df.Class

In [8]:
pca = PCA(n_components=3, whiten = False, random_state = 18)
X_pca = pca.fit_transform(x)
X_pca_reconst = pca.inverse_transform(X_pca)

In [10]:
print(X_pca_reconst)

[[ 4.52391535  3.18341872  0.6749867  ...  8.21393954 -0.02596261
   0.79344183]
 [ 4.52280888  3.17293304  0.67695161 ...  8.21541746 -0.0299796
   0.78773542]
 [ 4.42660673  3.2985026   0.58610553 ...  8.04583773 -0.04421958
   0.71312987]
 ...
 [ 5.3390109   2.78208057  0.75985306 ...  9.54455685  0.19035477
   0.41418301]
 [ 6.15092315 -1.87733537  3.3697643  ... 11.85807399 -0.6383606
   1.8940384 ]
 [ 5.05156365  2.58323412  1.11794707 ...  9.12396928  0.07319959
   1.15704878]]

In [15]:
#Using Pearson Correlation
plt.figure(figsize=(12,10))
cor = df.corr()
cor

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V33,V34,V35,V36,V37,V38,V39,V40,V41,Class
V1,1.000000,0.232683,0.261817,0.022219,0.185560,0.446789,0.423223,0.381464,0.202214,0.260533,...,0.311775,0.137806,0.033485,0.305638,0.101423,0.056802,0.489765,0.086938,0.339627,-0.396138
V2,0.232683,1.000000,0.067649,-0.094366,-0.186095,0.351183,-0.260477,-0.300082,0.150766,0.192826,...,-0.113457,-0.181558,0.009668,0.085867,0.513404,-0.088993,0.087903,-0.071860,0.389997,-0.001900
V3,0.261817,0.067649,1.000000,0.022182,0.003350,0.068106,0.258438,0.097963,-0.122079,-0.106941,...,0.439112,-0.036748,-0.135023,0.458958,0.051879,-0.042725,0.572485,-0.044127,0.542703,-0.299107
V4,0.022219,-0.094366,0.022182,1.000000,0.449388,0.006723,0.191410,-0.038907,0.024662,0.033042,...,0.212653,0.501351,0.134878,-0.005597,0.023329,0.462634,0.040402,-0.015143,0.000753,-0.103290
V5,0.185560,-0.186095,0.003350,0.449388,1.000000,0.001928,0.372453,0.146439,0.007436,0.086099,...,0.329136,0.789358,0.209706,0.041273,-0.030193,0.745717,0.147088,-0.043254,-0.021033,-0.234618
V6,0.446789,0.351183,0.068106,0.006723,0.001928,1.000000,0.079107,-0.062045,0.450833,0.042820,...,-0.030407,-0.037735,0.017497,0.014806,0.299743,-0.076978,0.121235,-0.037847,0.676194,-0.170450
V7,0.423223,-0.260477,0.258438,0.191410,0.372453,0.079107,1.000000,0.599244,0.135601,0.115968,...,0.800326,0.330718,0.113821,0.224343,-0.076045,0.183804,0.402740,0.112426,0.126977,-0.337268
V8,0.381464,-0.300082,0.097963,-0.038907,0.146439,-0.062045,0.599244,1.000000,-0.225157,-0.146550,...,0.409265,0.095466,-0.237641,0.149713,-0.249861,-0.091935,0.280505,0.117358,0.046641,-0.201603
V9,0.202214,0.150766,-0.122079,0.024662,0.007436,0.450833,0.135601,-0.225157,1.000000,0.189120,...,-0.075862,-0.031050,0.012466,-0.017843,-0.179416,-0.109209,0.031984,-0.021693,-0.046203,-0.056142
V10,0.260533,0.192826,-0.106941,0.033042,0.086099,0.042820,0.115968,-0.146550,0.189120,1.000000,...,0.104689,0.058491,0.200639,-0.033506,0.342116,0.026002,0.110323,0.217117,-0.121538,0.177183
V11,0.183770,-0.141810,-0.016309,0.424914,0.870518,-0.020331,0.333183,0.108752,-0.015423,0.093869,...,0.319698,0.803943,0.201959,0.025404,-0.018153,0.837190,0.131397,-0.044472,-0.037985,-0.242325
V12,-0.105155,-0.192385,0.059623,-0.052004,-0.091424,-0.164030,-0.096966,0.025884,0.043502,-0.502235,...,-0.025503,-0.048223,-0.217378,0.031164,-0.413455,-0.046133,-0.055758,-0.237699,-0.146301,-0.112425
V13,0.642858,0.043378,0.484630,0.087563,0.281696,0.269141,0.518167,0.352416,0.181067,0.326060,...,0.450910,0.204629,-0.052563,0.565551,-0.106991,0.107358,0.821144,0.121675,0.387417,-0.343779
V14,-0.113169,0.310928,-0.095576,-0.068655,-0.101403,-0.004951,-0.311625,-0.384364,0.262816,0.330236,...,-0.216984,-0.141718,-0.006971,-0.063082,-0.079421,-0.094091,-0.007827,0.059656,-0.058949,0.275321
V15,0.911546,0.115325,0.223020,0.077165,0.298373,0.404542,0.509044,0.429790,0.254276,0.364679,...,0.366130,0.247526,0.036621,0.252469,-0.047697,0.139046,0.514928,0.118278,0.283483,-0.343377
V16,0.415169,0.119643,-0.046508,0.008011,0.090350,0.134824,0.281869,0.059581,0.323677,0.840137,...,0.181229,0.020800,0.093617,0.054653,0.139426,-0.004170,0.222818,0.294269,-0.097428,-0.002879
V17,0.276838,0.491129,0.368722,0.026176,0.005295,0.389575,0.061432,-0.089817,-0.224501,0.219166,...,0.209678,-0.001029,0.067620,0.143145,0.853752,0.042820,0.225859,0.041499,0.669772,-0.091520
V18,-0.118332,0.444704,-0.321443,0.070722,-0.036033,0.485792,-0.452130,-0.682582,0.174310,0.088110,...,-0.357095,0.015464,0.219409,-0.263086,0.483644,0.153054,-0.326834,-0.077634,0.330402,0.131555
V19,-0.114219,-0.033522,-0.002863,0.386467,0.032674,-0.022657,-0.028561,-0.135041,-0.058793,-0.053722,...,0.000302,0.055435,0.180534,-0.047495,0.054333,0.143795,-0.071636,-0.013460,-0.006280,-0.059831
V20,0.114261,0.126076,-0.042696,0.019529,0.213351,-0.040700,0.182113,0.041622,-0.076635,0.236165,...,0.273389,0.289858,-0.045097,0.016910,0.251414,0.261664,0.067130,-0.028036,-0.024571,-0.153640
V21,0.234538,0.320962,0.145184,-0.022479,-0.011908,0.494523,-0.050939,-0.086156,0.049505,-0.078241,...,-0.041178,-0.027792,-0.068538,0.051244,0.386505,-0.048990,0.096025,-0.021650,0.562817,-0.096239
V22,0.230438,-0.257301,0.508299,-0.008287,0.085430,-0.213147,0.433985,0.623108,-0.127743,-0.369591,...,0.370252,0.045514,-0.305439,0.527758,-0.436441,-0.033224,0.590619,-0.015394,0.033794,-0.372254
V23,0.171793,-0.215989,0.086612,0.040820,0.524473,0.030420,0.265592,0.262763,-0.059339,-0.022657,...,0.088728,0.274838,-0.035838,0.096742,-0.093476,0.238271,0.143467,0.031737,0.023753,-0.116613
V24,-0.010448,-0.005467,0.321391,-0.033941,-0.064792,-0.014374,0.089057,0.035731,-0.034101,-0.097692,...,0.155984,-0.088615,-0.067016,0.610436,-0.052004,-0.101523,0.608400,-0.032690,0.215791,-0.114554
V25,0.138769,-0.006008,0.544763,0.107964,0.102038,-0.013056,0.279971,0.251518,-0.143819,-0.126987,...,0.432567,0.081202,-0.087005,0.123533,0.055358,0.039064,0.207031,-0.033375,0.334262,-0.252103
V26,0.054298,-0.142424,-0.050872,0.308158,0.382455,-0.006959,0.183080,0.138392,-0.022806,-0.097816,...,0.118353,0.376213,0.046459,0.018380,-0.103767,0.254453,0.050012,-0.010272,-0.042182,-0.091820
V27,0.918928,0.020384,0.222939,0.050725,0.269421,0.335782,0.515108,0.568842,0.089516,0.229444,...,0.368159,0.223197,0.005001,0.259384,-0.051569,0.124020,0.471681,0.123795,0.271577,-0.389951
V28,0.011154,-0.001269,0.004635,-0.003702,0.001478,0.003791,0.006773,0.017590,0.001984,-0.008008,...,0.005653,0.009245,-0.027970,0.036823,-0.015726,-0.001189,0.035637,0.001275,0.007416,-0.025022
V29,0.036602,-0.041310,0.294238,-0.027523,-0.044111,-0.028139,0.169451,0.144677,-0.067716,-0.084758,...,0.237724,-0.071859,-0.055909,0.494654,-0.091208,-0.087737,0.502901,-0.026509,0.191674,-0.092893
V30,0.259498,0.110712,-0.076078,0.120540,0.284368,-0.023455,0.204641,0.027982,0.009610,0.748379,...,0.185607,0.279073,0.081159,0.017179,0.361405,0.247257,0.163036,0.232852,-0.090311,0.053636
V31,-0.035091,-0.042344,-0.060299,0.072945,0.091057,0.046658,-0.014669,-0.134109,0.207682,0.350013,...,-0.011154,0.075846,0.011837,-0.068958,-0.213681,0.023508,0.100898,0.079318,-0.020684,0.173572
V32,0.232447,-0.203189,0.203298,-0.033625,-0.035533,0.223982,-0.122866,0.049967,-0.011669,-0.028309,...,-0.102725,-0.044478,-0.055872,-0.007834,-0.065989,-0.072977,0.032298,-0.023149,0.151909,-0.106590
V33,0.311775,-0.113457,0.439112,0.212653,0.329136,-0.030407,0.800326,0.409265,-0.075862,0.104689,...,1.000000,0.375060,0.150026,0.253413,0.044773,0.237154,0.406059,-0.030722,0.250781,-0.318547
V34,0.137806,-0.181558,-0.036748,0.501351,0.789358,-0.037735,0.330718,0.095466,-0.031050,0.058491,...,0.375060,1.000000,0.261641,-0.019022,-0.023156,0.802770,0.078988,-0.050809,-0.050630,-0.268875
V35,0.033485,0.009668,-0.135023,0.134878,0.209706,0.017497,0.113821,-0.237641,0.012466,0.200639,...,0.150026,0.261641,1.000000,-0.104896,0.244098,0.408499,-0.101894,-0.089686,-0.103258,-0.027387
V36,0.305638,0.085867,0.458958,-0.005597,0.041273,0.014806,0.224343,0.149713,-0.017843,-0.033506,...,0.253413,-0.019022,-0.104896,1.000000,-0.030303,-0.033724,0.917443,-0.010096,0.240311,-0.289619
V37,0.101423,0.513404,0.051879,0.023329,-0.030193,0.299743,-0.076045,-0.249861,-0.179416,0.342116,...,0.044773,-0.023156,0.244098,-0.030303,1.000000,0.050178,-0.026254,0.017971,0.410327,0.114896
V38,0.056802,-0.088993,-0.042725,0.462634,0.745717,-0.076978,0.183804,-0.091935,-0.109209,0.026002,...,0.237154,0.802770,0.408499,-0.033724,0.050178,1.000000,0.028250,-0.071083,-0.084558,-0.261751
V39,0.489765,0.087903,0.572485,0.040402,0.147088,0.121235,0.402740,0.280505,0.031984,0.110323,...,0.406059,0.078988,-0.101894,0.917443,-0.026254,0.028250,1.000000,0.038861,0.361664,-0.366793
V40,0.086938,-0.071860,-0.044127,-0.015143,-0.043254,-0.037847,0.112426,0.117358,-0.021693,0.217117,...,-0.030722,-0.050809,-0.089686,-0.010096,0.017971,-0.071083,0.038861,1.000000,-0.029295,0.149510
V41,0.339627,0.389997,0.542703,0.000753,-0.021033,0.676194,0.126977,0.046641,-0.046203,-0.121538,...,0.250781,-0.050630,-0.103258,0.240311,0.410327,-0.084558,0.361664,-0.029295,1.000000,-0.214476
Class,-0.396138,-0.001900,-0.299107,-0.103290,-0.234618,-0.170450,-0.337268,-0.201603,-0.056142,0.177183,...,-0.318547,-0.268875,-0.027387,-0.289619,0.114896,-0.261751,-0.366793,0.149510,-0.214476,1.000000

In [17]:
#Correlation with output variable
cor_target = abs(cor["Class"])

In [18]:
cor_target

V1       0.396138
V2       0.001900
V3       0.299107
V4       0.103290
V5       0.234618
V6       0.170450
V7       0.337268
V8       0.201603
V9       0.056142
V10      0.177183
V11      0.242325
V12      0.112425
V13      0.343779
V14      0.275321
V15      0.343377
V16      0.002879
V17      0.091520
V18      0.131555
V19      0.059831
V20      0.153640
V21      0.096239
V22      0.372254
V23      0.116613
V24      0.114554
V25      0.252103
V26      0.091820
V27      0.389951
V28      0.025022
V29      0.092893
V30      0.053636
V31      0.173572
V32      0.106590
V33      0.318547
V34      0.268875
V35      0.027387
V36      0.289619
V37      0.114896
V38      0.261751
V39      0.366793
V40      0.149510
V41      0.214476
Class    1.000000
Name: Class, dtype: float64

In [20]:
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.2]
relevant_features

V1       0.396138
V3       0.299107
V5       0.234618
V7       0.337268
V8       0.201603
V11      0.242325
V13      0.343779
V14      0.275321
V15      0.343377
V22      0.372254
V25      0.252103
V27      0.389951
V33      0.318547
V34      0.268875
V36      0.289619
V38      0.261751
V39      0.366793
V41      0.214476
Class    1.000000
Name: Class, dtype: float64